# Generated by Django 2.0.7 on 2018-07-09 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180709_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
